// <auto-generated />
using System;
using InfraEstructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraEstructure.Migrations
{
    [DbContext(typeof(ApplicationsDbContext))]
    partial class ApplicationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entity.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adress")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Adress");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Email");

                    b.Property<string>("Gender")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Gender");

                    b.Property<int>("IdentityCard")
                        .HasColumnType("int")
                        .HasColumnName("IdentityCard");

                    b.Property<string>("IdentityType")
                        .HasMaxLength(5)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("IdentityType");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("LastName");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.Property<string>("NumberPhone")
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("NumberPhone");

                    b.Property<string>("Profession")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Profession");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CityID");

                    b.HasKey("ID")
                        .HasName("PK_EMPLOYEE");

                    b.HasAlternateKey("IdentityCard")
                        .HasName("ALT_IDENTITY");

                    b.HasIndex(new[] { "ID" }, "UNIQID")
                        .IsUnique();

                    b.HasIndex(new[] { "IdentityCard" }, "UNIQ_IDENTITYCARD")
                        .IsUnique();

                    b.HasIndex(new[] { "NumberPhone" }, "UNIQ_NUMBERPHONE")
                        .IsUnique()
                        .HasFilter("[NumberPhone] IS NOT NULL");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
